### PR TITLE
Change EVP_MD_CTX for OpenSSL 1.1.0g

### PR DESCRIPTION
**Pull request by Dealaxer**

### CODE REVIEW

**Comment by smx-smx** [comment]
Hello, are you sure the code is equivalent? I tried compiling and it generated cast warnings. I will need to do some tests against epk files to make sure.
This code is responsible for the optional signature verification so it might not always be hit

**Comment by Dealaxer** [comment]
Hello! Yes, the code is absolutely working! I have with this code all compiled successfully!

**Comment by smx-smx** [comment]
Sadly, it looks like the most recent libssl version available through the Cygwin setup is 1.0.2n.
It would be a pity to introduce build troubles (or to require people to build openssl 1.1 on their own).
On the other hand, some linux distributions are settling with openssl 1.1 by default, and i encountered some issues while trying to get the older one detected (needs some additional flags to prefer the older version).

I would be leaning towards keeping OpenSSL 1.0 for the moment tho, since it's easily available on both Linux and Cygwin. Do you have any other suggestion?

**Comment by Dealaxer** [comment]
Just leave this change as a patch, for those who use or will use openssl 1.1. Or, you can make a selection option in the build script so that the person selects which version of openssl to use in the build.

**Comment by Pablohn26** [comment]
I was not able to compile using `openssl version OpenSSL 1.1.0h-fips  27 Mar 2018` on Fedora, but applying this patch I can compile. 

So I suppose make file should take in account the openssl version

**Comment by smx-smx** [comment]
I pushed a change to try and unify OpenSSL 1.0 and 1.1. Let me know if you have further problems

**Pull request closed without merging**
