### PR TITLE
adaptation for OpenSSL 1.1.0 with opaque EVP_MD_CTX

### PR DESCRIPTION
**Pull request by efa**

### CODE REVIEW

**Comment by smx-smx** [comment]
Hi, thanks for your interest in the project. Sadly, as mentioned in the other pull request, I can't commit something that would break OpenSSL 1.0 as that's the intended target for out of the box cygwin compatibility.
Maybe you can refactor this commit to work on both versions?
Your current proposal is causing build errors on Travis due to missing symbols

**Comment by efa** [comment]
in this pull request, pointers to structure are passed to functions by value, instead of pointer address, it is supposed pointer value does not change.
About support for both versions of OpenSSL, will try.

**Comment by boom1** [comment]
How about this:
[openssl_1_1_patch.txt](https://github.com/openlgtv/epk2extract/files/2534929/openssl_1_1_patch.txt)

**Comment by smx-smx** [comment]
I pushed a commit to try and unify OpenSSL 1.0 and 1.1.
Can you verify it works fine for you?
Remember to run epk2extract with -s to make use of the signature verification code

**Comment by boom1** [comment]
Thanks, it compiles and lzhs_scanner (sorry, I only use that) produces the same result as before (i.e. with my patch from above).

**Comment by efa** [comment]
compile well on both:
Ubuntu 16.04/Cygwin with openssl 1.0.2
and
Ubuntu 18.04 with openssl 1.1.0
cannot test Cygwin.

Your solution is coupled to OpenSSL 1.1 and its new API, while keep compatibility to 1.0 only when needed, while the 1.1 API offer always both symbols

**Comment by smx-smx** [comment]
Well then it's good, since cygwin uses 1.0.x and I tested it fine.

Yes it's similar to your patch, but it also has a preprocess #if to pick the right symbol name on both 1.0 and 1.1

About the goto, it really doesn't change much. The compiler can optimize that statement, and micro optimizations like that are not relevant, since the performance impact is not measurable or very tiny to be important

**Comment by efa** [comment]
just build on Cygwin:
CYGWIN_NT-6.1 myHOST 2.11.2(0.329/5/3) 2018-11-08 14:34 x86_64 Cygwin

**Pull request closed without merging**
